language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:

  - psql -c 'create database postgres;' -U postgres
  - python travis_tables.py
script:
  - pytest tests --cov=app --cov-report term-missing
after_success:
  - coveralls