language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - psql -c 'create database postgres;' -U postgres


  
script:
  - pytest tests --cov=app --cov-report term-missing
after_success:
  - coveralls